/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andium_cowsay_hci_CowSayConverter */

#ifndef _Included_com_andium_cowsay_hci_CowSayConverter
#define _Included_com_andium_cowsay_hci_CowSayConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andium_cowsay_hci_CowSayConverter
 * Method:    hci_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_andium_cowsay_hci_CowSayConverter_hci_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_andium_cowsay_hci_CowSayConverter
 * Method:    convert_to_cowsay
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_andium_cowsay_hci_CowSayConverter_convert_1to_1cowsay
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
